### ISSUE TITLE
rc/map: `m.without(k).0` names `__drop_tuple_(Map[K, V], boolean)` with the type params unsubstituted — the helper is never generated, `map_str_delete` fails to link on every backend under free-on

### ISSUE THREAD

**Issue by JakeChampion** [JakeChampion/lang#8707]
`TestX86_64FixturesFreeMatchesNoFree/map_str_delete`, `TestArm64FixturesFreeMatchesNoFree/map_str_delete` and `TestWASMFixturesFreeMatchesNoFree/map_str_delete` are red on main (`9af7fe265`):

```
ld: (.text+0x33c): undefined reference to `__drop_tuple__LP_Map_LB_K_C_V_RB__C_boolean_RP_'
ld: (.text+0x547): undefined reference to `__drop_tuple__LP_Map_LB_K_C_V_RB__C_boolean_RP_'
```

The fixture is `conformance/cases/map_str_delete`:

```fern
var m: Map[string, i32] = map_new(4);
m = m.insert("a", 1);
…
m = m.without("b").0;
m = m.without("c").0;
```

Bisected to 6a1fab014 (`rc/map(#8434, #8599)`, PR #8615), green at its parent.

## Cause

That commit's change 3 admits the seam-retained delete tuple in `freshOwnedFieldContainerType`, so the `.0` read deep-drops the tuple box through a `__drop_tuple_<mangled>` helper. The type it hands to the drop is `b.exprType(call)`, and for `__method_Map_delete` that is `callReturnType`'s answer: `info.FuncSigs["__method_Map_delete"].Result`, the **generic** signature `(Map[K, V], boolean)`. The mangled name therefore spells `K` and `V`. `dropFnNameFor` stashes that shape, the worklist's `genTupleDropFn` cannot plan a drop for a type variable and returns nil, the arm `continue`s, and the call site is left naming a function nothing generated.

`callReturnType` already special-cases `__method_Map_get_or`, `__method_MapIter_value` and `__method_MapIter_key` for exactly this reason ("the CONCRETE type is the call's TypeArg, not the generic FuncSig result"); `__method_Map_delete`'s tuple result was not one of them because, until #8615, nothing asked for its type as something to drop. The checker stamps `TypeArgs = [K, V]` on every Map method call, so the concrete type is available at the site.

The rc corpus cases #8615 added (`map_delete_projected_self_assign_churn_free`, `map_delete_projected_call_arg_churn_free`) do not catch this because they are typed `Map[string, i32]`… and still link — the corpus runs on the default (free-on) path, so the difference is which lowering path the fixture's `m = m.without(k).0` self-assign takes versus the corpus's shapes; that is worth pinning in the fix's test rather than guessed at here.

## Fix

Substitute the call's `TypeArgs` into the generic Map method result in `callReturnType` (there is `substituteTypeParamsDeep` in `rc_insert.go`) for every `__method_Map_*` rather than adding a fourth name to the switch, so the next Map method whose result type is asked for gets the concrete type too. Gate: `map_str_delete` under `Test{X86_64,Arm64,WASM}FixturesFreeMatchesNoFree`, plus an `internal/ir` test that lowers the fixture's shape and asserts every `__drop_tuple_` the ops name is a function in the program.

Refs #8615, #8434, #8599, #4451.

**Comment by JakeChampion** [comment]
Two halves, one landed. #8704 (f3fc0298b) gated the delete-tuple admission on `RcFreeEnabled`, which is what made the free-OFF leg name a helper no path generates; `map_str_delete` links again on all three backends. What remains is the naming: with reclamation ON the site still spells the helper `__drop_tuple_(Map[K, V], boolean)`, because both type paths read the generic Map signature. #8709 (rebased onto #8704) routes both through one TypeArgs-substituting `sigResultFor`, with a two-mode `internal/ir` test whose free-on half fails on current main.

---
_Generated by [Claude Code](https://claude.ai/code)_
